server:
  servlet:
    context-path: /connet-app
spring:
  application:
    name: connet-app
  datasource:
    url: jdbc:postgresql://ec2-54-165-90-230.compute-1.amazonaws.com:5432/davvbp39tq67rd
    username: qzuoqmgddehrwm
    password: c0f1be548839a1d0beccf7ea8b805a625ae6b93a6952a3f4b689388fff7de859
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        temp.use_jdbc_metadata_defaults: false
        format_sql: true
    show-sql: true
    generate-ddl: true
api:
  urlServer: 'http://localhost:8080/connet-app'
  name: 'API: @project.name@'
  description: '@project.description@'
  version: '@project.version@'
  client:
    host: 'https://connet-client-engine.herokuapp.com'
    v1:
      basePath: '/connet-client-engine/api/client/v1'
      clients: '/clients'
  installer:
    host: 'https://connet-installer-engine.herokuapp.com'
    v1:
      basePath: '/connet-installer-engine/api/installer/v1'
      installers: '/installers'
#  client:
#    host: 'http://localhost:8090'
#    v1:
#      basePath: '/connet-client-engine/api/client/v1'
#      clients: '/clients'
#  installer:
#    host: 'http://localhost:8091'
#    v1:
#      basePath: '/connet-installer-engine/api/installer/v1'
#      installers: '/installers'

